In [62]:
import numpy as np
import pandas as pd

In [63]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [64]:
cd /content/gdrive/My Drive/CSE4020_ML/lab6

/content/gdrive/My Drive/CSE4020_ML/lab6


In [65]:
ls

diabetes.csv


In [66]:
diabetes = pd.read_csv('diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

**Prediction using single hidden layer, logistic activation function.**

In [67]:
cols = diabetes.shape[1]

X = diabetes.iloc[:,0:cols-1]
Y = diabetes.iloc[:,cols-1]

print(X,Y)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  


In [68]:
pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [69]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

**Prediction using single hidden layer** 

In [70]:
mlp = MLPClassifier(hidden_layer_sizes=(100,),activation='logistic',max_iter=500,random_state=1)

X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.3,stratify=Y,random_state=1)

mlp.fit(X_train, y_train)

y = mlp.predict(X_test)

print("Accuracy = "+str(mlp.score(X_test,y_test)*100)+"%")
print("Epochs : 500")
print("")
#probability of having diabetes

probs = mlp.predict_proba(X) 

print(probs)

Accuracy = 72.72727272727273%
Epochs : 500

[[0.30726228 0.69273772]
 [0.92613982 0.07386018]
 [0.25011574 0.74988426]
 ...
 [0.6532756  0.3467244 ]
 [0.32808145 0.67191855]
 [0.90422996 0.09577004]]


**prediction using 2 hidden layers**

In [71]:
mlp = MLPClassifier(hidden_layer_sizes=(100,100),activation='logistic',max_iter=500,random_state=1)

X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.3,stratify=Y,random_state=1)

mlp.fit(X_train, y_train)

y = mlp.predict(X_test)

print("Accuracy = "+str(mlp.score(X_test,y_test)*100)+"%")
print("Epochs : 500")
print("")

#probability of having diabetes

probs = mlp.predict_proba(X) 

print(probs)

Accuracy = 73.16017316017316%
Epochs : 500

[[0.25799292 0.74200708]
 [0.96057629 0.03942371]
 [0.17053784 0.82946216]
 ...
 [0.66863496 0.33136504]
 [0.19053501 0.80946499]
 [0.92495751 0.07504249]]


**Using RELU activation function and single hidden layer and solver as gradient descent**


In [72]:
mlp = MLPClassifier(hidden_layer_sizes=(100,),activation='relu',solver='sgd',max_iter=500,random_state=1)

X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.3,stratify=Y,random_state=1)

mlp.fit(X_train, y_train)

y = mlp.predict(X_test)

print("Accuracy = "+str(mlp.score(X_test,y_test)*100)+"%")
print("Epochs : 500")
print("")

#probability of having diabetes

probs = mlp.predict_proba(X) 

print(probs)

Accuracy = 68.83116883116884%
Epochs : 500

[[0.3205856  0.6794144 ]
 [0.67467499 0.32532501]
 [0.18013155 0.81986845]
 ...
 [0.62127418 0.37872582]
 [0.37293714 0.62706286]
 [0.76007022 0.23992978]]


**Using RELU activation function and 2 hidden layers and solver as gradient descent** 

In [73]:
mlp = MLPClassifier(hidden_layer_sizes=(100,100),activation='relu',solver='sgd',max_iter=500,random_state=1)

X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.3,stratify=Y,random_state=1)

mlp.fit(X_train, y_train)

y = mlp.predict(X_test)

print("Accuracy = "+str(mlp.score(X_test,y_test)*100)+"%")
print("Epochs : 500")
print("")

#probability of having diabetes

probs = mlp.predict_proba(X) 

print(probs)

Accuracy = 65.36796536796537%
Epochs : 500

[[0.41270429 0.58729571]
 [0.8508888  0.1491112 ]
 [0.24734931 0.75265069]
 ...
 [0.57159814 0.42840186]
 [0.55482156 0.44517844]
 [0.88951571 0.11048429]]


**Normalizing the Data**

In [74]:
from sklearn.preprocessing import normalize

In [75]:
Xnorm = normalize(X)

mlp = MLPClassifier(hidden_layer_sizes=(100,),activation='logistic',max_iter=500,random_state=1)

X_train, X_test, y_train, y_test = train_test_split(Xnorm,Y,test_size=0.3,stratify=Y,random_state=1)

mlp.fit(X_train, y_train)

y = mlp.predict(X_test)

print("Accuracy = "+str(mlp.score(X_test,y_test)*100)+"%")
print("Epochs : 500")
print("")

#probability of having diabetes

probs = mlp.predict_proba(Xnorm) 

print(probs)


Accuracy = 63.20346320346321%
Epochs : 500

[[0.65551478 0.34448522]
 [0.80587136 0.19412864]
 [0.47564626 0.52435374]
 ...
 [0.64301021 0.35698979]
 [0.62384211 0.37615789]
 [0.8021317  0.1978683 ]]


**Pandas Correlation**

In [76]:
print(diabetes.corr())

                          Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221

In the correlation matrix above, age and pregnancies are approximately correlated.

In [77]:
#X has only 2 features namely age and pregnancies
X = diabetes.iloc[:,[0,cols-2]]

Y = diabetes.iloc[:,cols-1]

In [78]:
mlp = MLPClassifier(hidden_layer_sizes=(100,),activation='relu',solver='sgd',max_iter=500,random_state=1)

X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.3,stratify=Y,random_state=1)

mlp.fit(X_train, y_train)

y = mlp.predict(X_test)

print("Accuracy = "+str(mlp.score(X_test,y_test)*100)+"%")

Accuracy = 64.5021645021645%
